version: "3"

services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    ports:
      - 54325:5432
    env_file: docker/.env

  t-rex:
    build: ./docker/t-rex
    volumes:
      - ./settings/trex.toml:/config/config.toml
    depends_on:
      - postgres
    ports:
      - 6767:6767

  web:
    image: httpd:2.4
    volumes:
     - ./web/:/usr/local/apache2/htdocs/
    ports:
      - 8082:80
