
version: "3"
services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    ports:
      - 54325:5432
    env_file: docker/.env
  importer:
    image: openmaptiles/import-osm
    env_file: docker/.env
    volumes:
     - ./docker/imposm/import:/import
     - ./settings/imposm_import.yml:/mapping/mapping.yaml
     - ./settings/post-process.sql:/mapping/post-process.sql
    depends_on:
      - postgres
  t-rex:
    build: ./docker/t-rex
    volumes:
      - ./settings/trex.toml:/config/config.toml
    depends_on:
      - postgres
    ports:
      - 6767:6767
