# t-rex configuration

[service.mvt]
viewer = true

[[datasource]]
name = "vapour"
dbconn = "postgresql://vapour:vapour@postgres/vapour"

[grid]
# Predefined grids: web_mercator, wgs84
predefined = "web_mercator"

[[tileset]]
name = "vapour_trail"

[[tileset.layer]]
name = "stops"
table_name = "d_stops"
geometry_field = "geom"
geometry_type = "POINT"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 10

[[tileset.layer]]
name = "stops_shield"
table_name = "d_stops_shield"
geometry_field = "geom"
geometry_type = "POINT"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 14

[[tileset.layer]]
name = "ways"
table_name = "d_ways"
geometry_field = "geom"
geometry_type = "LINESTRING"
srid = 3857
#fid_field = "id"
buffer_size = 2
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 12

[[tileset.layer]]
name = "routes_position"
table_name = "d_routes_position"
geometry_field = "geom"
geometry_type = "POINT"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
minzoom = 14

#[cache.file]
#base = "/srv/mvtcache"
#baseurl = "http://example.com/tiles"

[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "0.0.0.0"
port = 6767
threads = 4
#cache_control_max_age = 43200
